---
- name: apt install sslh
  apt:
    name: sslh
    state: present

- name: set config path
  lineinfile:
    path: /etc/default/sslh
    regexp: '^DAEMON_OPTS='
    line: "DAEMON_OPTS='--config /etc/sslh/sslh.cfg'"

- name: sslh config dir
  file:
    path: /etc/sslh
    state: directory

- name: sslh config file
  template:
    src: templates/sslh.cfg.j2
    dest: /etc/sslh/sslh.cfg
  register: sslh_config

- name: sslh transparent support
  copy:
    src: files/90-local-lo.yaml
    dest: /etc/netplan/
  register: netplan_config

- name: netplay apply
  command: netplan apply
  when: netplan_config is changed

- name: sslh restart
  systemd:
    name: sslh
    state: restarted
  when: sslh_config is changed
