---
- name: apt install sslh
  apt:
    name: sslh
    state: present

- name: set config path
  lineinfile:
    path: /etc/default/sslh
    regexp: '^DAEMON_OPTS='
    line: "DAEMON_OPTS='--config /etc/sslh/sslh.cfg'"

- name: sslh config dir
  file:
    path: /etc/sslh
    state: directory

- name: sslh config file
  copy:
    src: files/sslh.cfg
    dest: /etc/sslh/sslh.cfg
  register: sslh_config

- name: sslh transparent support - sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-local.conf
  with_items:
     - name: net.ipv4.conf.default.route_localnet
       value: 1
     - name: net.ipv4.conf.all.route_localnet
       value: 1

- name: sslh transparent support - apply iptables rules to lo
  replace:
    path: /etc/ufw/before.rules
    regexp: '^(-A ufw-before.* lo .*)'
    replace: '#\1'

- name: sslh transparent support - iptables mark packets
  blockinfile:
    path: /etc/ufw/before.rules
    block: |
      *raw
      -A PREROUTING ! -i lo -d 127.0.0.0/8 -j DROP
      COMMIT

      *nat
      -A OUTPUT -m owner --uid-owner sslh -p tcp --tcp-flags FIN,SYN,RST,ACK SYN -j CONNMARK --set-xmark 0x01/0x0f
      COMMIT

      *mangle
      -A POSTROUTING ! -o lo -s 127.0.0.0/8 -j DROP
      -A OUTPUT ! -o lo -p tcp -m connmark --mark 0x01/0x0f -j CONNMARK --restore-mark --mask 0x0f
      COMMIT
  register: ufw_before

- name: ufw reload
  ufw:
    state: reloaded
  when: ufw_before is changed

- name: sslh transparent support - routing
  copy:
    src: files/90-local-lo.yaml
    dest: /etc/netplan/
  register: netplan_config

- name: netplay apply
  command: netplan apply
  when: netplan_config is changed

- name: sslh restart
  systemd:
    name: sslh
    state: restarted
  when: sslh_config is changed
