---
- name: get thelounge
  get_url:
    url: https://github.com/thelounge/thelounge/releases/download/v3.2.0/thelounge_3.2.0-1_all.deb
    dest: /root/
  register: thelounge_deb

- name: apt install thelounge
  apt:
    deb: /root/thelounge_3.2.0-1_all.deb
  when: thelounge_deb is changed

- set_fact:
    thelounge_config_path: /etc/thelounge/config.js

- name: bind localhost
  replace:
    path: "{{ thelounge_config_path }}"
    regexp: 'host: undefined,'
    replace: "host: '127.0.0.1',"

- name: enable properties
  replace:
    path: "{{ thelounge_config_path }}"
    regexp: "{{ item }}: false,"
    replace: "{{ item }}: true,"
  with_items:
    - prefetch
    - prefetchStorage
    - reverseProxy

- name: disable log globally
  replace:
    path: "{{ thelounge_config_path }}"
    regexp: 'messageStorage: .*,'
    replace: 'messageStorage: [],'
