---
- name: get thelounge
  get_url:
    url: https://github.com/thelounge/thelounge/releases/download/v3.2.0/thelounge_3.2.0-1_all.deb
    checksum: 'sha256:42a130b57395fdcd0f3b966f5e01375fc56ae12fc7281b1927cd88d99ba68df6'
    dest: /root/thelounge_3.2.0-1_all.deb
  register: thelounge_deb

- name: apt install thelounge
  apt:
    deb: /root/thelounge_3.2.0-1_all.deb
  when: thelounge_deb is changed

- set_fact:
    thelounge_config_path: /etc/thelounge/config.js

- name: bind localhost
  replace:
    path: "{{ thelounge_config_path }}"
    regexp: 'host: undefined,'
    replace: "host: '127.0.0.1',"
  register: thelounge_bind

- name: enable properties
  replace:
    path: "{{ thelounge_config_path }}"
    regexp: "{{ item }}: false,"
    replace: "{{ item }}: true,"
  with_items:
    - prefetch
    - prefetchStorage
    - reverseProxy

- name: disable log globally
  replace:
    path: "{{ thelounge_config_path }}"
    regexp: 'messageStorage: .*,'
    replace: 'messageStorage: [],'

- name: restart thelounge
  systemd:
    name: thelounge
    state: restarted
  when: thelounge_bind is changed

- name: reverse proxy for the lounge
  template:
    src: templates/thelounge.apache2.conf
    dest: /etc/apache2/sites-available/{{ web_irc_fqdn }}.conf
  register: thelounge_rproxy

- name: apache2 reload
  systemctl:
    name: apache2
    state: reloaded
  when: thelounge_rproxy is changed
