network:
  version: 2
  renderer: networkd
  ethernets:
    lo:
      match:
        name: lo
      routing-policy:
       - priority: 100
         from: 0.0.0.0/0
         mark: 1
         table: 100
