  - job_name: 'grafana_metrics'
    static_configs:
    - targets: ['localhost:2990']

  - job_name: node
    static_configs:
    - targets:
      - 'localhost:9100'
      - 'darkbox.t.739141.xyz:9100'
      - 'tokyo-jumpbox.t.739141.xyz:9100'

  - job_name: apache
    static_configs:
    - targets:
      - 'localhost:9117'

  - job_name: blackbox
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://nobuto-murata.org
        # TLSv1.3 doesn't work out of the box
        #- https://grafana.t.739141.xyz:3000/login
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115

  - job_name: blackbox_icmp
    metrics_path: /probe
    params:
      module: [icmp]
    scrape_timeout: 800ms  # icmp timeout to be 300ms with 500ms offset
    static_configs:
      - targets: []
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
