  - job_name: 'grafana_metrics'
    static_configs:
    - targets: ['localhost:2990']

  - job_name: libvirt
    static_configs:
    - targets: ['quick-maas.t.739141.xyz:9178']

  - job_name: node
    static_configs:
    - targets:
      - 'localhost:9100'
      - 'darkbox.t.739141.xyz:9100'
      - 'quick-maas.t.739141.xyz:9101'
      - 'tokyo-jumpbox.t.739141.xyz:9100'

  - job_name: maas
    static_configs:
    - targets:
      - 'quick-maas.t.739141.xyz:5238' # regiond
      - 'quick-maas.t.739141.xyz:5248' # rackd

  - job_name: maas
    metrics_path: /MAAS/metrics
    static_configs:
    - targets:
      - 'quick-maas.t.739141.xyz:5241' # maas
