  - job_name: 'grafana_metrics'
    static_configs:
    - targets: ['localhost:2990']

  - job_name: node
    static_configs:
    - targets:
      - 'localhost:9100'
      - 'darkbox.t.739141.xyz:9100'
      - 'tokyo-jumpbox.t.739141.xyz:9100'

  - job_name: apache
    static_configs:
    - targets:
      - 'localhost:9117'
