---
- name: snap install prometheus
  snap:
    name: prometheus
    channel: 2/stable
    state: present

- name: apt install - prometheus exporters
  apt:
    name:
    - prometheus-node-exporter
    - prometheus-apache-exporter
    - prometheus-blackbox-exporter
    state: present

- name: prometheus - localhost binding
  lineinfile:
    path: /var/snap/prometheus/current/daemon_arguments
    regexp: '^ARGS='
    line: 'ARGS="--web.listen-address=127.0.0.1:9090"'

- name: scrape configurations
  blockinfile:
    path: /var/snap/prometheus/current/prometheus.yml
    block: "{{ lookup('file', 'files/prometheus_scrape_configs.yml') }}"

- name: restart prometheus
  systemd:
    name: snap.prometheus.prometheus
    state: restarted
  changed_when: False

- name: add Grafana apt key
  apt_key:
    id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
    url: https://packages.grafana.com/gpg.key
    keyring: /etc/apt/trusted.gpg.d/grafana.gpg

- name: add Grafana apt repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: apt install grafana
  apt:
    name: grafana
    state: present

- name: grafana - localhost binding
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;*http_addr ='
    line: 'http_addr = 127.0.0.1'

- name: grafana - change the default port in favor of nginx
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^;*http_port = '
    line: 'http_port = 2990'

- name: grafana - grafana-piechart-panel
  command: grafana-cli plugins install grafana-piechart-panel
  changed_when: False

- name: enable and start grafana-server
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: install nginx
  apt:
    name: nginx
    state: present

- name: nginx - disable the default site
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /var/www/html/index.nginx-debian.html

- name: install the reverse proxy definition but not enable it
  copy:
    src: files/sites-available/grafana
    dest: /etc/nginx/sites-available/grafana

- name: certbot-dns-cloudflare - allow the plugin
  command: snap set certbot trust-plugin-with-root=ok
  changed_when: False

- name: certbot-dns-cloudflare - install
  snap:
    name: certbot-dns-cloudflare
    state: present
