---
- name: snap install prometheus
  snap:
    name: prometheus
    channel: 2/stable
    state: present

- name: apt install prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: scrape node-exporter
  blockinfile:
    path: /var/snap/prometheus/current/prometheus.yml
    block: |2
        - job_name: node
          static_configs:
          - targets:
            - 'localhost:9100'
            - '100.118.229.71:9100' # darkbox, TODO: use a hostname
            - '100.98.232.3:9100' # tokyo-jumpbox

- name: restart prometheus
  systemd:
    name: snap.prometheus.prometheus
    state: restarted
  changed_when: False

- name: add Grafana apt key
  apt_key:
    id: 4E40DDF6D76E284A4A6780E48C8C34C524098CB6
    url: https://packages.grafana.com/gpg.key
    keyring: /etc/apt/trusted.gpg.d/grafana.gpg

- name: add Grafana apt repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: apt install grafana
  apt:
    name: grafana
    state: present

- name: enable and start grafana-server
  systemd:
    name: grafana-server
    enabled: yes
    state: started
