---
- name: snap install prometheus
  snap:
    name: prometheus
    channel: 2/stable
    state: present

- name: apt install prometheus-node-exporter
  apt:
    name: prometheus-node-exporter
    state: present

- name: scrape node-exporter
  blockinfile:
    path: /var/snap/prometheus/current/prometheus.yml
    block: |2
        - job_name: node
          static_configs:
          - targets: ['localhost:9100']

- name: restart prometheus
  systemd:
    name: snap.prometheus.prometheus
    state: restarted
  changed_when: False
