---
- name: 'sysctl - LP: #1899852 for IPv6'
  sysctl:
    name: net.ipv6.ip_nonlocal_bind
    value: '1'
    sysctl_file: /etc/sysctl.d/99-local.conf

- name: apt install apache2
  apt:
    name: apache2
    state: present

- name: snap install certbot
  snap:
    name: certbot
    classic: yes
    state: present

- name: listen on alternative port for HTTPS
  template:
    src: templates/ports.conf
    dest: /etc/apache2/ports.conf
  register: bind_port

- name: enable modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ssl
    - http2
    - headers
    - rewrite

- name: restart apache2
  systemd:
    name: apache2
    state: restarted
  when: bind_port is changed

- name: disable the default site
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/sites-enabled/000-default.conf
    - /var/www/html/index.html

- name: set fallback site
  copy:
    src: files/sites-available/000-fallback.apache2.conf
    dest: /etc/apache2/sites-available/000-fallback.conf

- name: enable fallback site
  file:
    src: /etc/apache2/sites-available/000-fallback.conf
    dest: /etc/apache2/sites-enabled/000-fallback.conf
    state: link

- name: copy www-home contents
  copy:
    src: files/www-home/
    dest: /var/www/www-home/

- name: install www-home site but not enable it
  copy:
    src: files/sites-available/www-home.conf
    dest: /etc/apache2/sites-available/www-home.conf

- name: reload apache2
  systemd:
    name: apache2
    state: reloaded
  changed_when: False
