---
- name: auto-restart services on package update
  block:
    - debconf:
        name: libc6
        question: libraries/restart-without-asking
        value: 'true'
        vtype: boolean
    - debconf:
        name: libc6
        question: libraries/restart-without-asking
        value: 'true'
        vtype: seen

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: apt dist-upgrade
  apt:
    upgrade: dist

- name: apt install etckeeper
  apt:
    name: etckeeper
    state: present
