---
- name: debconf auto-restart services on package update
  debconf:
    name: libc6
    question: libraries/restart-without-asking
    value: 'true'
    vtype: boolean

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: apt dist-upgrade
  apt:
    upgrade: dist

- name: apt install etckeeper
  apt:
    name: etckeeper
    state: present

- name: enable ufw but allow everything
  ufw:
    state: enabled
    default: allow

- name: get ssh ports
  shell: "grep '^Port ' /etc/ssh/sshd_config | awk '{print $2}'"
  register: ssh_ports
  changed_when: false

- name: ufw limit ssh
  ufw:
    rule: limit
    port: "{{ item }}"
    proto: tcp
    comment: ssh
  with_items: "{{ ssh_ports.stdout_lines | default(22, true) }}"
