---
- name: apt install apache2
  apt:
    name: apache2
    state: present

- mame: listen on alternative ports
  replace:
    path: /etc/apache2/ports.conf
    regexp: 'Listen {{ item.orig }}$'
    replace: 'Listen {{ item.new }}'
  with_items:
    - orig: 80
      new: 70
    - orig: 443
      new: 433
  register: bind_port

- name: enable modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ssl
    - headers
    - rewrite
    - proxy
    - proxy_http
    - proxy_wstunnel

- name: restart apache2
  systemd:
    name: apache2
    state: restarted
  when: bind_port is changed
