---
- name: apt install apache2
  apt:
    name: apache2
    state: present

- name: apt install certbot and apache plugin
  apt:
    name: [certbot, python3-certbot-apache]
    state: present

- mame: listen on alternative port for HTTPS
  replace:
    path: /etc/apache2/ports.conf
    regexp: 'Listen 443$'
    replace: 'Listen 433'
  register: bind_port

- name: enable modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - ssl
    - headers
    - rewrite

- name: disable the default site
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/sites-enabled/000-default.conf
    - /var/www/html/index.html

- name: set fallback site
  copy:
    src: files/000-fallback.apache2.conf
    dest: /etc/apache2/sites-available/000-fallback.conf
  register: thelounge_rproxy

- name: enable fallback site
  file:
    src: /etc/apache2/sites-available/000-fallback.conf
    dest: /etc/apache2/sites-enabled/000-fallback.conf
    state: link

- name: restart apache2
  systemd:
    name: apache2
    state: restarted
  when: bind_port is changed
