---
- name: apt install apache2
  apt:
    name: apache2
    state: present

- mame: listen on alternative ports
  replace:
    path: /etc/apache2/ports.conf
    regexp: 'Listen {{ port.orig }}$'
    replace: 'Listen {{ port.new }}'
  var:
    port:
      - orig: 80
        new: 70
      - orig: 443
        new: 433
  register: bind_port

- name: restart apache2
  systemd:
    name: apache2
    state: restarted
  when: bind_port is changed
